### ISSUE TITLE
[Mod Incompatibility] [Forge 1.18.2] Pressing e with jei installed on the jei search bar force closes your inventory

### ISSUE THREAD

**Issue by thelegitdolt** [isXander/Debugify#74]
Reproduce: 

1. Download JEI mod
2. CLick on the jei search bar
3. type the letter E
4. observe that the inventory closes despite its search bar being selected

Since JEI is pretty much in every single modpack to ever exist, I think fixing this bug would benefit a lot of players :)

I've no clue which bug out of the 60 that this mod fixes is causing this, though. Sorry about that.

**Comment by isXander** [comment]
Please use the template :/ what version of debugify are you using?

**Comment by thelegitdolt** [comment]
latest 1.9.0 version i believe

**Comment by logwet** [comment]
I can confirm that disabling the patch for [MC-147605](https://bugs.mojang.com/browse/MC-147605) in Debugify settings resolves this issue for me. I'm using Debugify `1.9.0` and JEI `9.7.0.193`

**Comment by EthanDevelops** [comment]
Fixed in latest JEI version @isXander

**Comment by thelegitdolt** [comment]
i am currently using the latest JEI version, .193, and it the bug still seems to persist, unless this is indev or something

**Comment by isXander** [comment]
@EthanDevelops

**Comment by EthanDevelops** [comment]
Hmm

**Comment by logwet** [comment]
> Fixed in latest JEI version @isXander

The last update to the JEI branch on the repo was 8 days ago, 2 days before either this issue or the corresponding issue on the JEI repo (mezz/JustEnoughItems#2801) was created. What release or version are you referring to?

**Comment by isXander** [comment]
I think the report was referring to Debugify's latest version where issues surrounding this fix were present.

**Comment by border999** [comment]
I've been using the jei-1.18.2-9.7.0.194 and keeping debugify up to date. I'm getting the same issue, gonna use the solution that was presented here.

**Comment by StarskyXIII** [comment]
I have same issue with Controlling Search bar.
With lastest version Debugify and Controlling .

**Comment by Leonime** [comment]
Just to add to the problem, it's not just JEI, at first I tough the problem was with JEI but it was not, it's every text box, for some reason keybindings are being triggered on textboxes, making it almost impossible to type anything depending on the quantity of mods you have. (I'm using debugify-1.11.0)

**Comment by mezz** [comment]
Hi @isXander, this bug seems to fix a very niche problem but has some wide-ranging compatibility complications with mods, would you consider disabling this particular fix by default? 
I think it would take a lot more work to make this fix friendly to mods because input handling in Minecraft is such a difficult and often questionable area of the code.

**Comment by isXander** [comment]
> Hi @isXander, this bug seems to fix a very niche problem but has some wide-ranging compatibility complications with mods, would you consider disabling this particular fix by default? I think it would take a lot more work to make this fix friendly to mods because input handling in Minecraft is such a difficult and often questionable area of the code.

Sure, I will disable it for now while I fix the issue.

**Comment by isXander** [comment]
I'm going to mark this as duplicate of #135 as it outlines the underlying cause of the bug.

**Comment by Prebentyse1212** [comment]
> I can confirm that disabling the patch for [MC-147605](https://bugs.mojang.com/browse/MC-147605) in Debugify settings resolves this issue for me. I'm using Debugify `1.9.0` and JEI `9.7.0.193`

then how do you find that

**Comment by XionioXMaster** [comment]
1.18.2
